apiVersion: v1
kind: Service
metadata:
  name: keyvault-test-app
  namespace: {{ default "keyvault-test" .Release.Namespace }}
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: keyvault-test-app
  type: ClusterIP